<?php

/**
 * @file
 * Adding theme function for adding twig file.
 */

/**
 * Implements hook_theme().
 */
function googlemap_block_theme() {
  $items = [];
  $items['googlemap_block'] = [
    'variables' => [
      'map_height' => NULL,
      'map_width' => NULL,
    ],
  ];
  return $items;
}

/**
 * Return latitude and longitude.
 */
function googlemap_block_lat_long($address) {
  if (!empty($address)) {
    // Formatted address.
    $formattedAddr = str_replace(' ', '+', $address);
    // Send request and receive json data by address.
    $geocodeFromAddr = file_get_contents('http://maps.googleapis.com/maps/api/geocode/json?address=' . urlencode($formattedAddr) . '&sensor=false');
    $output = json_decode($geocodeFromAddr);
    // Get latitude and longitute from json data.
    $data['latitude'] = $output->results[0]->geometry->location->lat;
    $data['longitude'] = $output->results[0]->geometry->location->lng;
    // Return latitude and longitude of the given address.
    if (!empty($data)) {
      return $data;
    }
  }
}
